name: "Deploy to AWS"

# trigger the owrkflow from the github ui

on: workflow_dispatch
    

jobs:
    deploy: 
        runs-on: self-hosted

        steps:
           - name: "Setup NodeJS"
             uses: actions/setup-python@v5
             with:
                 python-version: '3.11'

           - name: "checkout code"
             uses:  actions/checkout@v4     

           - name: "Install dependencies "
             run: |
               python -m pip install --upgrade pip
               pip install django
           - name: "Run migrations"
             run: |
              python manage.py migrate  
        
           



